### ISSUE TITLE
Need export maxLines, and add Expaneded

### ISSUE THREAD

**Issue by Leadrive** [herrytco/Flutter-HTML-Editor#1]
Hi, in the desktop app,
Need export maxLines, and add Expaneded.

selectable_textfield.dart
line 78
maxLines: null,

If I need the editor full height,
editor.dart
line 330
add Expanded

**Comment by herrytco** [comment]
`maxLines` was added as a property of the `EditorDecoration`. The editor itself is full-height by default but if there is no content, then there is no information to display also, `Expanded(..)` wouldn't change that.
