### ISSUE TITLE
can you posibble to add undo redo option?

### ISSUE THREAD

**Issue by Govindbetterlives** [herrytco/Flutter-HTML-Editor#5]
Hi, 
How can I add undo redo option in this widget? And also not over right the HTML code like this.

![image](https://user-images.githubusercontent.com/81243940/192756086-d2db996e-50b2-41ef-aa87-d56ab4fa661e.png)

**Comment by Govindbetterlives** [comment]
Yes, it should undo the recent add tag operation and also need to replace the existing tag with a given tag.
In the above example. In the span tag, only the color should be replaced. It should not add any new span tag. The same applies to all the tags like header<H1, H2, H3>.

**Comment by herrytco** [comment]
I added a first version of the preview feature to the editor, please test it and tell me what you think :)

**Comment by herrytco** [comment]
The problem with the nested tag-creation should be fixed by the last version (21) as well.
